project:
  type: book
  execute-dir: project

book:
  title: "Endogenous Macrodynamics in Algorithmic Recourse"
  author: 
    - name: Patrick Altmeyer
      url: https://www.paltmeyer.com/
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Giovan Angela
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Aleksander Buszydlik
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Karol Dobiczek
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Arie van Deursen
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Cynthia C. S. Liem
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
  date: "22/12/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - notebooks/appendix.qmd
    - references.qmd

crossref:
  fig-prefix: Figure
  tbl-prefix: Table

bibliography: bib.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png

execute: 
  freeze: auto
  eval: true
  echo: true
  output: false

jupyter: julia-1.8



