project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  title: "Endogenous Macrodynamics in Algorithmic Recourse"
  author: 
    - name: Patrick Altmeyer
      url: https://www.paltmeyer.com/
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Giovan Angela
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Aleksander Buszydlik
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Karol Dobiczek
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Arie van Deursen
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
    - name: Cynthia C. S. Liem
      affiliation: Delft University of Technology
      affiliation-url: https://www.tudelft.nl/en/
  date: "22/12/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - sections/data_preprocessing/index.qmd
    - sections/experiments/synthetic.qmd
    - sections/experiments/real_world.qmd
    - sections/experiments/mitigation_strategies.qmd
    - sections/generators/index.qmd
    - references.qmd

crossref:
  fig-prefix: Figure
  tbl-prefix: Table

bibliography: bib.bib

format:
  html:
    theme: cosmo
  epub:
    cover-image: paper/www/poc.png

execute: 
  freeze: auto
  eval: true
  echo: true
  output: false

jupyter: julia-1.8



