[dev-artifacts-upload-data-real_world]
git-tree-sha1 = "d94351a362f68f369bdbc51bdc75a41a979cb9e4"
lazy = true

    [[dev-artifacts-upload-data-real_world.download]]
    sha256 = "135aca8e600e3ce7c38d813f6ed805f86bb9624c94b8746912a81f7a54f9a951"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-real_world.tar.gz"

[dev-artifacts-upload-data-synthetic]
git-tree-sha1 = "badee6b6f85fdc2c80b18a34c7640e49b550027c"
lazy = true

    [[dev-artifacts-upload-data-synthetic.download]]
    sha256 = "07d20a01d2e76636b8d33644a195cb49391cc74b2400806b7e307b9a80d2785a"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-synthetic.tar.gz"

[dev-artifacts-upload-output-real_world]
git-tree-sha1 = "eb55d50f8f07b87c97c2049697ae606df86b13d4"
lazy = true

    [[dev-artifacts-upload-output-real_world.download]]
    sha256 = "ba0e753fe430b9605366b852c6457df5fa2d0bd3cae90f828090f4f1bec1d8b7"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-output-real_world.tar.gz"

[dev-artifacts-upload-output-synthetic]
git-tree-sha1 = "d81bc078e85ef8c7b255e39d620edbdc98795e69"
lazy = true

    [[dev-artifacts-upload-output-synthetic.download]]
    sha256 = "704c05de484d694aa7563c76b32f0810622aee1761f61101226e1b0934ea7a34"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-output-synthetic.tar.gz"

[dev-artifacts-upload-www-real_world]
git-tree-sha1 = "ceb45c40d527d9e4ab0888f5fc07a0519ba04702"
lazy = true

    [[dev-artifacts-upload-www-real_world.download]]
    sha256 = "f4d3ca2ff572affa5e443667bbcfa0461f9f300e681a5d74450584b37a224b58"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-www-real_world.tar.gz"

[dev-artifacts-upload-www-synthetic]
git-tree-sha1 = "351f47768dbc33d8a0cbcb55b46703230bd69c4e"
lazy = true

    [[dev-artifacts-upload-www-synthetic.download]]
    sha256 = "08300d62dd0cbcf65a17d629dc87d4242bbcc908e57af6613ed34363b27ba9fd"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-www-synthetic.tar.gz"
