[dev-artifacts-upload-data-real_world]
git-tree-sha1 = "786855bd41ee89331d55d8cf3f48168cf6229fc7"
lazy = true

    [[dev-artifacts-upload-data-real_world.download]]
    sha256 = "d41970b8c0b94a0605bf03cb5085351aced8da2a4ecfd8b84450ad2b46507525"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/dec-2022/dev-artifacts-upload-data-real_world.tar.gz"

[dev-artifacts-upload-data-synthetic]
git-tree-sha1 = "badee6b6f85fdc2c80b18a34c7640e49b550027c"
lazy = true

    [[dev-artifacts-upload-data-synthetic.download]]
    sha256 = "f34f0a8956249f609337bd32fb0226439aa14aabe01fb7a46b5d9846b4a9151b"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/dec-2022/dev-artifacts-upload-data-synthetic.tar.gz"

[dev-artifacts-upload-output-mitigation_strategies]
git-tree-sha1 = "b13bc41f544109a60356e91bef7820740b2051d4"
lazy = true

    [[dev-artifacts-upload-output-mitigation_strategies.download]]
    sha256 = "3b8d3078ced9b75cbc2c2c202f609cf445dfc281ba64b977a5cfd7a2de1e2ad7"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-mitigation_strategies.tar.gz"

[dev-artifacts-upload-output-real_world]
git-tree-sha1 = "4d8de5eab707e33774170d4c96725e2243fce8e2"
lazy = true

    [[dev-artifacts-upload-output-real_world.download]]
    sha256 = "37f7ab1b1d1645e6eedd8537cfb62c91d9203468b85bc86a05441565567d43db"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-real_world.tar.gz"

[dev-artifacts-upload-output-synthetic]
git-tree-sha1 = "d7b2a896881527a958c790bee5d101184062a667"
lazy = true

    [[dev-artifacts-upload-output-synthetic.download]]
    sha256 = "95376dd72d5895062ff9182a8259b307efdd16872511cc61e10b1bbcbf7ee912"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-synthetic.tar.gz"

[dev-artifacts-upload-www-mitigation_strategies]
git-tree-sha1 = "7c68bb624bab60703d133283098c53c2321efab3"
lazy = true

    [[dev-artifacts-upload-www-mitigation_strategies.download]]
    sha256 = "14de2d23c8d5db5e9624ceb25fbc19048a38846b783f241874b8fb90598987dc"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-www-mitigation_strategies.tar.gz"

[dev-artifacts-upload-www-real_world]
git-tree-sha1 = "24b6e883fd4f13baf6f2f9421d326a92187ea3f5"
lazy = true

    [[dev-artifacts-upload-www-real_world.download]]
    sha256 = "6c6df464afa36f1e326ca6d7e8c4fce9c483585646625d6235285df3bf4a088e"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-www-real_world.tar.gz"

[dev-artifacts-upload-www-synthetic]
git-tree-sha1 = "f3cbdb255993a17ed9fae6031af0d244ad04dadc"
lazy = true

    [[dev-artifacts-upload-www-synthetic.download]]
    sha256 = "e5a4e21a7186df3709be70b6b96e3cb76c9312c05e36d3598dd3b83610a1fcb1"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-www-synthetic.tar.gz"
