[dev-artifacts-upload-data-real_world]
git-tree-sha1 = "d94351a362f68f369bdbc51bdc75a41a979cb9e4"
lazy = true

    [[dev-artifacts-upload-data-real_world.download]]
    sha256 = "135aca8e600e3ce7c38d813f6ed805f86bb9624c94b8746912a81f7a54f9a951"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-real_world.tar.gz"

[dev-artifacts-upload-data-synthetic]
git-tree-sha1 = "2bb01d9cdfed8d41983725b07aaa52ed2b1334e6"
lazy = true

    [[dev-artifacts-upload-data-synthetic.download]]
    sha256 = "181da6139a6531eed62130508d85b659fd40dc096daf2ccf06154f7da6b654eb"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-synthetic.tar.gz"
