[dev-artifacts-upload-data-real_world]
git-tree-sha1 = "786855bd41ee89331d55d8cf3f48168cf6229fc7"
lazy = true

    [[dev-artifacts-upload-data-real_world.download]]
    sha256 = "d41970b8c0b94a0605bf03cb5085351aced8da2a4ecfd8b84450ad2b46507525"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/dec-2022/dev-artifacts-upload-data-real_world.tar.gz"

[dev-artifacts-upload-data-synthetic]
git-tree-sha1 = "badee6b6f85fdc2c80b18a34c7640e49b550027c"
lazy = true

    [[dev-artifacts-upload-data-synthetic.download]]
    sha256 = "f34f0a8956249f609337bd32fb0226439aa14aabe01fb7a46b5d9846b4a9151b"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/dec-2022/dev-artifacts-upload-data-synthetic.tar.gz"

[dev-artifacts-upload-output-mitigation_strategies]
git-tree-sha1 = "b13bc41f544109a60356e91bef7820740b2051d4"
lazy = true

    [[dev-artifacts-upload-output-mitigation_strategies.download]]
    sha256 = "3b8d3078ced9b75cbc2c2c202f609cf445dfc281ba64b977a5cfd7a2de1e2ad7"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-mitigation_strategies.tar.gz"

[dev-artifacts-upload-output-real_world]
git-tree-sha1 = "4d8de5eab707e33774170d4c96725e2243fce8e2"
lazy = true

    [[dev-artifacts-upload-output-real_world.download]]
    sha256 = "37f7ab1b1d1645e6eedd8537cfb62c91d9203468b85bc86a05441565567d43db"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-real_world.tar.gz"

[dev-artifacts-upload-output-synthetic]
git-tree-sha1 = "d7b2a896881527a958c790bee5d101184062a667"
lazy = true

    [[dev-artifacts-upload-output-synthetic.download]]
    sha256 = "95376dd72d5895062ff9182a8259b307efdd16872511cc61e10b1bbcbf7ee912"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/jan-2023/dev-artifacts-upload-output-synthetic.tar.gz"

[dev-artifacts-upload-www]
git-tree-sha1 = "4203e173fa695af5751d90d7fd73752d8c590010"
lazy = true

    [[dev-artifacts-upload-www.download]]
    sha256 = "7bde31191fc1cfec9ccea86b8b3a3b49c1f9f414407c4a4d6cf01918d09e848a"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/thesis/dev-artifacts-upload-www.tar.gz"

[dev-artifacts-upload-www-mitigation_strategies]
git-tree-sha1 = "012968c638f907c436a2e4b06e03cd1bfadc7cc9"
lazy = true

    [[dev-artifacts-upload-www-mitigation_strategies.download]]
    sha256 = "48659116aef35312708117065245bbea6ff9edbcf2a4d0e49fa47db10e22752a"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/thesis/dev-artifacts-upload-www-mitigation_strategies.tar.gz"

[dev-artifacts-upload-www-real_world]
git-tree-sha1 = "3ddccd46cb2e509f365549dd81052b22b82642e8"
lazy = true

    [[dev-artifacts-upload-www-real_world.download]]
    sha256 = "b8d4a4d5d236fd6bea9f5510c09be5f46772f89ff8ec425ff92f092e59c6da44"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/thesis/dev-artifacts-upload-www-real_world.tar.gz"

[dev-artifacts-upload-www-synthetic]
git-tree-sha1 = "ca6c07b03498bafd627a5552612f09370e6b9a7a"
lazy = true

    [[dev-artifacts-upload-www-synthetic.download]]
    sha256 = "35a8649ad4a7bf21b7429845b21ec95e88895d98e90255eab9156c7e18f73402"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/thesis/dev-artifacts-upload-www-synthetic.tar.gz"
