[data]
git-tree-sha1 = "590ac20e723afbca8c6f414eca14f845223a437a"
lazy = true

    [[data.download]]
    sha256 = "5a15a423e911443889d9a954917133d45f54bee65699f6cd201852f1f1c7d66d"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/data.tar.gz"

[output]
git-tree-sha1 = "086afa8f4efe460e08d4e64582c873ef31294b60"
lazy = true

    [[output.download]]
    sha256 = "6383094bb584574d5c2ec05093d024f780f0fbe301711c5972d96be807136155"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/output.tar.gz"

[www]
git-tree-sha1 = "be2f5c26e9666aa8c04c241970fbb7813a4a8407"
lazy = true

    [[www.download]]
    sha256 = "cb05546c6d45589cbcffaad7c72c6ccb9f927af66128af8d6f2502876016ff15"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/www.tar.gz"
