[dev-artifacts-upload-data-real_world]
git-tree-sha1 = "d94351a362f68f369bdbc51bdc75a41a979cb9e4"
lazy = true

    [[dev-artifacts-upload-data-real_world.download]]
    sha256 = "135aca8e600e3ce7c38d813f6ed805f86bb9624c94b8746912a81f7a54f9a951"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-real_world.tar.gz"

[dev-artifacts-upload-data-synthetic]
git-tree-sha1 = "2bb01d9cdfed8d41983725b07aaa52ed2b1334e6"
lazy = true

    [[dev-artifacts-upload-data-synthetic.download]]
    sha256 = "181da6139a6531eed62130508d85b659fd40dc096daf2ccf06154f7da6b654eb"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-data-synthetic.tar.gz"

[dev-artifacts-upload-output-real_world]
git-tree-sha1 = "48384ce8d681a46cbd0338a06523be09abbf95e2"
lazy = true

    [[dev-artifacts-upload-output-real_world.download]]
    sha256 = "c259664c0eea4b5ef46398d1dabbc062f7ca0e5c16a904af6d8e816d93535947"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-output-real_world.tar.gz"

[dev-artifacts-upload-www-real_world]
git-tree-sha1 = "38a90db898aa40f81e0ca10a8c9c81209953d620"
lazy = true

    [[dev-artifacts-upload-www-real_world.download]]
    sha256 = "7726b036ea60e32ace45a6bc0a20ad8e4b57e7218c9a078e93490fd9ee43fdea"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/dev-artifacts-upload-www-real_world.tar.gz"
