[data]
git-tree-sha1 = "902bd7e623196b898d323cd974f8dbd5a5329690"
lazy = true

    [[data.download]]
    sha256 = "b6049da449edf6505bf52a72022db0ecc1cdcd6d8f48d55ab529597287b482d7"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/data.tar.gz"

[output]
git-tree-sha1 = "086afa8f4efe460e08d4e64582c873ef31294b60"
lazy = true

    [[output.download]]
    sha256 = "985704f59c63bbf5742fd9be1b0031db87e70b2e8dbea6f9be4e06efe371fbfd"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/output.tar.gz"

[www]
git-tree-sha1 = "be2f5c26e9666aa8c04c241970fbb7813a4a8407"
lazy = true

    [[www.download]]
    sha256 = "73b2bb14c94d7378023f77cf2f429362454220a2bf86bbb519c308785c0b9f5d"
    url = "https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse/releases/download/camera-ready/www.tar.gz"
